[package]
name = "dcim"
version = "1.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "dcim"
path = "src/bin/cli.rs"

[lib]
name = "dcim"
path = "src/lib.rs"

[dependencies]
rug = "1.16.0"
lazy_static = "1.4.0"